# Generated by Django 4.0.10 on 2023-03-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
